"""
Live analytics dashboard for the Adaptive Traffic Signal Control project.

Reads the files detect_and_signal.py and simulate_comparison.py already
write to outputs/ - it doesn't run detection itself, so it stays lightweight
and can be left open in a browser tab while detect_and_signal.py runs in
its own OpenCV window.

Run with:
    streamlit run dashboard.py
"""

import os
import json
import time

import pandas as pd
import streamlit as st

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUTS_DIR = os.path.join(BASE_DIR, "outputs")

LATEST_RUN_PATH = os.path.join(OUTPUTS_DIR, "latest_run.json")
TELEMETRY_PATH = os.path.join(OUTPUTS_DIR, "telemetry.csv")
COMPARISON_JSON_PATH = os.path.join(OUTPUTS_DIR, "comparison.json")
COMPARISON_CHART_PATH = os.path.join(OUTPUTS_DIR, "comparison_chart.png")
STATE_PATH = os.path.join(BASE_DIR, "signal_state.json")

st.set_page_config(page_title="Adaptive Traffic Signal - Dashboard", layout="wide")

st.title("Adaptive Traffic Signal Control - Live Dashboard")
st.caption("Reads the output files written by detect_and_signal.py and simulate_comparison.py.")


def load_json(path):
    if not os.path.exists(path):
        return None
    try:
        with open(path, "r") as f:
            return json.load(f)
    except (ValueError, OSError):
        return None


latest_run = load_json(LATEST_RUN_PATH)

if latest_run is None:
    st.warning("No run data yet. Run `python detect_and_signal.py` first, then refresh.")
else:
    age_s = time.time() - latest_run["timestamp"]
    st.caption("Last detection run: {:.0f} seconds ago".format(age_s))

    labels = latest_run["labels"]
    plan = latest_run["plan"]
    emergency_flags = latest_run["emergency_flags"]

    if any(emergency_flags):
        emergency_lanes = [label for label, flag in zip(labels, emergency_flags) if flag]
        st.error("EMERGENCY VEHICLE DETECTED - preempting: {}".format(", ".join(emergency_lanes)))

    st.subheader("Current signal plan")
    cols = st.columns(len(labels))
    for col, label, p in zip(cols, labels, plan):
        with col:
            badge = " 🚨" if p["emergency"] else ""
            st.metric(label + badge, "{:.0f}s green".format(p["green"]), "{} vehicles".format(p["count"]))
            st.caption("served {:.0f} | carries over {:.0f} | waited {} cycle(s)".format(
                p["served"], p["leftover"], p.get("cycles_waited", 0)))

    st.subheader("Green time allocation")
    plan_df = pd.DataFrame({
        "Lane": labels,
        "Green (s)": [p["green"] for p in plan],
        "Detected": [p["count"] for p in plan],
        "Served": [p["served"] for p in plan],
        "Carries over": [p["leftover"] for p in plan],
    }).set_index("Lane")
    st.bar_chart(plan_df["Green (s)"])
    st.dataframe(plan_df, use_container_width=True)

    st.metric("Total cycle time", "{:.0f}s".format(latest_run["total_cycle_time"]))

    if os.path.exists(TELEMETRY_PATH):
        st.subheader("Vehicle count over the run (per lane)")
        telemetry_df = pd.read_csv(TELEMETRY_PATH)
        pivot = telemetry_df.pivot_table(index="elapsed_s", columns="lane", values="count", aggfunc="max")
        pivot = pivot.ffill()
        st.line_chart(pivot)

state = load_json(STATE_PATH)
if state is not None:
    st.subheader("Carried-over backlog (persists between runs)")
    backlog = state.get("backlog", [])
    cycles_waited = state.get("cycles_waited", [0] * len(backlog))
    if backlog:
        backlog_df = pd.DataFrame({
            "Lane": ["Lane {}".format(i + 1) for i in range(len(backlog))],
            "Backlog": backlog,
            "Cycles waited": cycles_waited,
        }).set_index("Lane")
        st.bar_chart(backlog_df["Backlog"])

st.divider()
st.header("Before / after: fixed-timer vs. adaptive")
st.caption("Generated by `python simulate_comparison.py` - simulates repeated signal cycles under both policies.")

comparison = load_json(COMPARISON_JSON_PATH)
if comparison is None:
    st.info("No comparison data yet. Run `python simulate_comparison.py` first, then refresh.")
else:
    c1, c2, c3 = st.columns(3)
    c1.metric("Avg queue length reduced", "{:.1f}%".format(comparison["backlog_improvement_pct"]))
    c2.metric("Fixed-timer final backlog", "{:.0f} vehicles".format(comparison["fixed_timer"]["final_backlog"]))
    c3.metric("Adaptive final backlog", "{:.0f} vehicles".format(comparison["adaptive"]["final_backlog"]))

    if os.path.exists(COMPARISON_CHART_PATH):
        st.image(COMPARISON_CHART_PATH, use_container_width=True)

    compare_long_df = pd.DataFrame({
        "Cycle": list(range(1, comparison["num_cycles"] + 1)) * 2,
        "Backlog": comparison["fixed_timer"]["backlog_over_time"] + comparison["adaptive"]["backlog_over_time"],
        "Scheme": ["Fixed-timer"] * comparison["num_cycles"] + ["Adaptive"] * comparison["num_cycles"],
    })
    st.line_chart(compare_long_df, x="Cycle", y="Backlog", color="Scheme")

st.divider()
st.header("SUMO validation (independent traffic simulator)")
st.caption("Generated by `python sumo_sim/traci_control.py --mode both` - drives a real SUMO "
           "microsimulation through TraCI using this project's exact compute_signal_plan().")

sumo_comparison = load_json(os.path.join(OUTPUTS_DIR, "sumo_comparison.json"))
if sumo_comparison is None or "fixed" not in sumo_comparison or "adaptive" not in sumo_comparison:
    st.info("No SUMO comparison yet. Run `python sumo_sim/traci_control.py --mode both` first, then refresh.")
else:
    fixed_stats = sumo_comparison["fixed"]
    adaptive_stats = sumo_comparison["adaptive"]

    s1, s2, s3 = st.columns(3)
    s1.metric("Avg waiting time reduced", "{:.1f}%".format(sumo_comparison.get("waiting_time_improvement_pct", 0)))
    s2.metric("Fixed-timer avg wait", "{:.1f}s".format(fixed_stats["avg_waiting_time"]))
    s3.metric("Adaptive avg wait", "{:.1f}s".format(adaptive_stats["avg_waiting_time"]))

    sumo_df = pd.DataFrame({
        "Metric": ["Completed trips", "Avg waiting time (s)", "Avg trip duration (s)", "Avg time loss (s)"],
        "Fixed-timer": [fixed_stats["completed_trips"], fixed_stats["avg_waiting_time"],
                        fixed_stats["avg_duration"], fixed_stats["avg_time_loss"]],
        "Adaptive": [adaptive_stats["completed_trips"], adaptive_stats["avg_waiting_time"],
                     adaptive_stats["avg_duration"], adaptive_stats["avg_time_loss"]],
    }).set_index("Metric")
    st.dataframe(sumo_df, use_container_width=True)

st.divider()
if st.button("Refresh now"):
    st.rerun()
st.caption("This page does not auto-refresh - click Refresh (or re-run detect_and_signal.py / simulate_comparison.py and reload).")
